spring:
  config:
    activate:
      on-profile: local
  cache:
    type: caffeine
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

management:
  health:
    redis:
      enabled: false

storage:
  local:
    cdn-base-url: ${LOCAL_STORAGE_CDN_BASE_URL:}
