spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: ${REDIS_TIMEOUT:2s}
  cache:
    type: redis
